<?php
/** @var \AHT\Sa\Block\Template $block */
    $cssClass = $this->hasCssClass() ? '' . $this->getCssClass() : '';
    $products = $block->getProducts();
    $item1 = $block->getData('item1');
?>

<div class="product_commission">
    <h1>Product Assignes</h1>
    <table class="table-commission">
        <tr>
            <th>STT</th>
            <th>Product Name</th>
            <th>SKU</th>
            <th>URL</th>
            <th>Commission Type</th>
            <th>Commission Value</th>
            <th>price</th>
        </tr>
    <?php foreach ($products as $key => $value) :?>
        <tr>
            <td><?= $key ?></td>
            <td><?= $value->getName() ?></td>
            <td><?= $value->getSku() ?></td>
            <td><a href="<?= $value->getProductUrl() ?>">View</a></td>
            <td><?= $value->getCommissionType() == 1 ? "Fixed" : "Percent" ?></td>
            <td>
                <?= $value->getCommissionValue() ?>
                <?= $value->getCommissionType() == 1 ? " $" : " %" ?>
            </td>
            <td><?= $block->roundPrice($value->getPrice()) . ' $' ?></td>
        </tr>
    <?php endforeach ?>
    </table>

</div>